<a href="https://colab.research.google.com/github/Engvatcharb/data-science-bootcamp9/blob/main/Engvatcharb/data-science-bootcamp9/Project10_Python/Essential_Python_for_Data_Analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Essential Python for DA

In [1]:
print ("Hello World")

Hello World


## OOP

In [2]:
class ATM:
    pass

In [4]:
from random import randint

class ATM:
    def __init__(self,account_name,bank_name,initial): ##
        self.account_name = account_name
        self.bank_name = bank_name
        self.balance = initial
    ## string representation
    def __str__(self):
        return f"this is an account of {self.account_name}, bank: {self.bank_name}"

    ## method is the builded function for this class
    def check_balance(self):
        print(f"Balance: {self.balance} THB")

    def deposit (self,money):
       self.balance += money
       print (f"Deposit successfully: your new balance: {self.balance} THB")

    def withdraw(self,money):
       self.balance -= money
       print (f"Withdraw successfully: your new balance: {self.balance} THB")

    def get_OTP():
        otp = randint(1000,9999)
        ## {otp} not have {self.otp} because not define in __init__
        print(f"Your OTP: {otp} This OTP will be available in the next 2 minutes")


In [5]:
## Create an instance from ATM Class
acc1 = ATM("Jenny","scb",500)

In [6]:
acc1.bank_name

'scb'

In [7]:
# code is for human
print(acc1)

this is an account of Jenny, bank: scb


In [8]:
acc1.check_balance()

Balance: 500 THB


In [9]:
acc1.deposit(100)

Deposit successfully: your new balance: 600 THB


In [10]:
acc1.withdraw(50)

Withdraw successfully: your new balance: 550 THB


In [11]:
import random

random.randint(1000,9999)

2447

In [12]:
ATM.get_OTP()

Your OTP: 6423 This OTP will be available in the next 2 minutes


## Try Except Block

In [13]:
try:
    ## 1/0 print "cannot divide by zero"
    1/5 # 0.2 print Done
except ZeroDivisionError:
    print ("cannot divide by zero")
except NameError:
    print("variable not defined")
else:
    print("Done")
finally:  ## print final all case
    print ("Complete!")

Done
Complete!


## import csv


In [16]:
## import csv
import csv
try:
    file = open("friend.csv")
    data = csv.reader(file)
    for row in data:
        print(row)
    file.close()
except FileNotFoundError:
    print("File not found.")

['id', 'name', 'age', 'city']
['1', 'toy', '35', 'bangkok']
['2', 'john', '32', 'london']
['3', 'mary', '28', 'seol']


In [17]:
## context manager
result = []
## With open and close file automatically
try:
    with open("friend.csv") as file:
        data = csv.reader(file)
        for row in data:
            result.append(row)
except:
    print ("file not found")
else:
    print("load data successfully")
finally:
    print(result)
print(result)

load data successfully
[['id', 'name', 'age', 'city'], ['1', 'toy', '35', 'bangkok'], ['2', 'john', '32', 'london'], ['3', 'mary', '28', 'seol']]
[['id', 'name', 'age', 'city'], ['1', 'toy', '35', 'bangkok'], ['2', 'john', '32', 'london'], ['3', 'mary', '28', 'seol']]


In [18]:
!pwd ## ! is magic command

/content


In [19]:
#make folder
!mkdir cat

In [20]:
!cat friend.csv

id,name,age,city
1,toy,35,bangkok
2,john,32,london
3,mary,28,seol


In [21]:
!rmdir cat

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [23]:
## Another way to read file of csv by using libary of pandas
import pandas as pd
try:
     df = pd.read_csv("friend.csv")
except:
     print ("a little error")

In [24]:
## write csv file using pandas
df.to_csv ("newCSVFile.csv")

In [25]:
!ls

chinook.db  data.json  drive  friend.csv  newCSVFile.csv  sample_data  store.csv


In [26]:
## write csv using csv module
import csv

col_name = ["food_id","food","price"]

data = [
    [1,"pizza",200],
    [2,"french fried",50],
    [3,"coke",10]
]

with open("food.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(col_name)
    writer.writerows(data)

In [27]:
!cat food.csv

food_id,food,price
1,pizza,200
2,french fried,50
3,coke,10


## JSON

In [37]:
## json = dictionary in Python
import json

# read file
with open("data.json","r") as file:
    result1 = json.load(file)

print(result1)

{'id': 1, 'name': 'toy', 'favorite_food': ['coke', 'pizza']}


In [39]:
result1['name'] = "Jenny"

In [40]:
result1.get("favorite_food")[1]

'pizza'

In [41]:
## Add more data data in favorite_food
result1["favorite_food"].append("hamburger")
result1

{'id': 1, 'name': 'Jenny', 'favorite_food': ['coke', 'pizza', 'hamburger']}

In [42]:
result1["favorite_food"].remove("hamburger")
result1

{'id': 1, 'name': 'Jenny', 'favorite_food': ['coke', 'pizza']}

In [44]:
result1["city"] = "New York"
result1

{'id': 1,
 'name': 'Jenny',
 'favorite_food': ['coke', 'pizza'],
 'city': 'New York'}

In [46]:
from json import load,dump

## with = ??
with open ("JohhWick,json","w") as file:
    json.dump(result1,file,indent=6)
    print("successfully dump a new json file.")

successfully dump a new json file.


## API #

Application Programming Interface


In [48]:
## using library of requests for using url get
import requests

url = "https://swapi.dev/api/people/1"

requests.get(url)

<Response [200]>

## ** Numpy & Pandas **


Numerical python
pandas dataframe

In [49]:
import numpy as np
import pandas as pd

In [50]:
nums = [1,20,25,30,100] ## vector c(1,20,25,30,100) in R

In [51]:
## normally if you don't use numpy so you use aggregation not more by use only sum,min,max but count and std can not use
## so this you can use numpy for can use all aggregate function
sum(nums)

176

In [52]:
min(nums)

1

In [53]:
## numpy array
arr_nums = np.array(nums)

In [54]:
np.sum(arr_nums)

176

In [55]:
## Call function
print(
    np.sum(arr_nums),
    np.mean(arr_nums),
    np.median(arr_nums),
    np.min(arr_nums),
    np.max(arr_nums),
    np.std(arr_nums)
)

176 35.2 25.0 1 100 33.85498486190771


In [57]:
## call method
arr_nums.sum()

176

In [ ]:
arr_nums.std()

33.85498486190771

In [58]:
## vector in R
m1 = np.array([
   [1,2],
   [3,4]
]
)

In [59]:
print(m1)

[[1 2]
 [3 4]]


In [60]:
## element wise computation
## broadcasting
print(m1 + 100)
print(m1 * 5)

[[101 102]
 [103 104]]
[[ 5 10]
 [15 20]]


In [61]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [63]:
## function arange mean  print start = 1 end 101 (not include 101) by increasing +1
np.arange(1,101,1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [64]:
np.arange(1,101,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
## this function of linspace mean you print oly 5 number between 1 and 101
np.linspace(1, 101, 5) ## list only 5 number

array([  1.,  26.,  51.,  76., 101.])

In [ ]:
np.linspace(1, 101, 10)

array([  1.        ,  12.11111111,  23.22222222,  34.33333333,
        45.44444444,  56.55555556,  67.66666667,  78.77777778,
        89.88888889, 101.        ])

In [65]:
# matrix dot notation
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,5],[3,2]])
print (m1)
print (m2)
np.dot(m1,m2)

[[1 2]
 [3 4]]
[[5 5]
 [3 2]]


array([[11,  9],
       [27, 23]])

In [66]:
m1.dot(m2)

array([[11,  9],
       [27, 23]])

In [75]:
import pandas as pd

data = {
    "id":[1,2,3],
    "name":["Jenny","Nat","North"],
    "city":["BKK","London","Newyork"]
}
df1 = pd.DataFrame(data)
df1

id   name     city
0   1  Jenny      BKK
1   2    Nat   London
2   3  North  Newyork

In [76]:
df1["age"] = [35,28,29]
df1

id   name     city  age
0   1  Jenny      BKK   35
1   2    Nat   London   28
2   3  North  Newyork   29

In [77]:
df1.drop("age",axis=1) #1 is columns

id   name     city
0   1  Jenny      BKK
1   2    Nat   London
2   3  North  Newyork

In [78]:
## read csv file from pandas
df = pd.read_csv("store.csv")
df.head(2)

Row ID        Order ID  Order Date   Ship Date     Ship Mode Customer ID  \
0       1  CA-2016-152156  2016-11-08  2016-11-11  Second Class    CG-12520   
1       2  CA-2016-152156  2016-11-08  2016-11-11  Second Class    CG-12520   

  Customer Name   Segment        Country       City  ... Postal Code  Region  \
0   Claire Gute  Consumer  United States  Henderson  ...       42420   South   
1   Claire Gute  Consumer  United States  Henderson  ...       42420   South   

        Product ID   Category Sub-Category  \
0  FUR-BO-10001798  Furniture    Bookcases   
1  FUR-CH-10000454  Furniture       Chairs   

                                        Product Name   Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.96         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94         3   

   Discount    Profit  
0       0.0   41.9136  
1       0.0  219.5820  

[2 rows x 21 columns]

In [79]:
df.shape #attribute

(9994, 21)

In [80]:
df.columns ## attribute

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [81]:
df.info() ## method

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [82]:
df.shape  #attribute

(9994, 21)

In [84]:
## query() google sheet ==> filter rows wtih conditions
## clean dataframe columns names
clean_col_names=[]
col_names = list(df.columns)
col_names
for name in col_names:
    clean_col_names += [name.lower().replace(" ","_").replace("-","_")]

In [85]:
df.columns = clean_col_names
df.head()

row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335   

     customer_name    segment        country             city  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  postal_code  region       product_id         category sub_category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        product_name     sales  quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   discount    profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [86]:
df.tail(n=5)

row_id        order_id  order_date   ship_date       ship_mode  \
9989    9990  CA-2014-110422  2014-01-21  2014-01-23    Second Class   
9990    9991  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9991    9992  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9992    9993  CA-2017-121258  2017-02-26  2017-03-03  Standard Class   
9993    9994  CA-2017-119914  2017-05-04  2017-05-09    Second Class   

     customer_id     customer_name   segment        country         city  ...  \
9989    TB-21400  Tom Boeckenhauer  Consumer  United States        Miami  ...   
9990    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...   
9991    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...   
9992    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...   
9993    CC-12220      Chris Cortes  Consumer  United States  Westminster  ...   

     postal_code  region       product_id         category sub_category  \
9989       33180   South  FUR-FU-10001889        Furniture  Furnishings   
9990       92627    West  FUR-FU-10000747        Furniture  Furnishings   
9991       92627    West  TEC-PH-10003645       Technology       Phones   
9992       92627    West  OFF-PA-10004041  Office Supplies        Paper   
9993       92683    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           product_name    sales  quantity  \
9989                             Ultra Door Pull Handle   25.248         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960         2   
9991                              Aastra 57i VoIP phone  258.576         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2   

      discount   profit  
9989       0.2   4.1028  
9990       0.0  15.6332  
9991       0.2  19.3932  
9992       0.0  13.3200  
9993       0.0  72.9480  

[5 rows x 21 columns]

In [87]:
## data transformation (R dplyr)
df2 = df[["customer_id","customer_name"]].head(5)


In [88]:
## query
df[ df["customer_name"] == "Claire Gute" ][["order_date","customer_id","customer_name"]]

order_date customer_id customer_name
0     2016-11-08    CG-12520   Claire Gute
1     2016-11-08    CG-12520   Claire Gute
5491  2017-01-26    CG-12520   Claire Gute
6877  2015-10-15    CG-12520   Claire Gute
6878  2015-10-15    CG-12520   Claire Gute

In [100]:
## query

df.query(" city == 'Los Angeles' and category == 'Furniture' and sub_category == 'Tables' ")[["customer_name","segment","city"]].head(5)

customer_name      segment         city
10    Brosina Hoffman     Consumer  Los Angeles
282     Jas O'Carroll     Consumer  Los Angeles
557       Olvera Toch     Consumer  Los Angeles
1097     Noel Staavos    Corporate  Los Angeles
1505    Pauline Chand  Home Office  Los Angeles

In [102]:
## aggregate data
## region = "West"

res = df.query("region == 'West'" )\
      .groupby(["segment","region"])[["sales","profit"]]\
      .agg(['sum','mean','count'])\
      .reset_index()
print(res)

res.to_csv("agg_data.csv")

       segment region        sales                        profit             \
                               sum        mean count         sum       mean   
0     Consumer   West  362880.7730  217.033955  1672  57450.6040  34.360409   
1    Corporate   West  225855.2745  235.265911   960  34437.4299  35.872323   
2  Home Office   West  136721.7770  239.442692   571  16530.4150  28.949939   

         
  count  
0  1672  
1   960  
2   571  


## Load data from SQL

In [103]:
import sqlite3
import pandas as pd

## create connection
con = sqlite3.connect("chinook.db")

pd.read_sql("select * from customers where country = 'USA'",con)

CustomerId FirstName    LastName                Company  \
0           16     Frank      Harris            Google Inc.   
1           17      Jack       Smith  Microsoft Corporation   
2           18  Michelle      Brooks                   None   
3           19       Tim       Goyer             Apple Inc.   
4           20       Dan      Miller                   None   
5           21     Kathy       Chase                   None   
6           22   Heather     Leacock                   None   
7           23      John      Gordon                   None   
8           24     Frank     Ralston                   None   
9           25    Victor     Stevens                   None   
10          26   Richard  Cunningham                   None   
11          27   Patrick        Gray                   None   
12          28     Julia     Barnett                   None   

                      Address            City State Country  PostalCode  \
0   1600 Amphitheatre Parkway   Mountain View    CA     USA  94043-1351   
1             1 Microsoft Way         Redmond    WA     USA  98052-8300   
2                627 Broadway        New York    NY     USA  10012-2612   
3             1 Infinite Loop       Cupertino    CA     USA       95014   
4        541 Del Medio Avenue   Mountain View    CA     USA   94040-111   
5            801 W 4th Street            Reno    NV     USA       89503   
6            120 S Orange Ave         Orlando    FL     USA       32801   
7             69 Salem Street          Boston    MA     USA        2113   
8       162 E Superior Street         Chicago    IL     USA       60611   
9       319 N. Frances Street         Madison    WI     USA       53703   
10        2211 W Berry Street      Fort Worth    TX     USA       76110   
11            1033 N Park Ave          Tucson    AZ     USA       85719   
12                302 S 700 E  Salt Lake City    UT     USA       84102   

                Phone                Fax                     Email  \
0   +1 (650) 253-0000  +1 (650) 253-0000        fharris@google.com   
1   +1 (425) 882-8080  +1 (425) 882-8081   jacksmith@microsoft.com   
2   +1 (212) 221-3546  +1 (212) 221-4679         michelleb@aol.com   
3   +1 (408) 996-1010  +1 (408) 996-1011          tgoyer@apple.com   
4   +1 (650) 644-3358               None       dmiller@comcast.com   
5   +1 (775) 223-7665               None       kachase@hotmail.com   
6   +1 (407) 999-7788               None        hleacock@gmail.com   
7   +1 (617) 522-1333               None    johngordon22@yahoo.com   
8   +1 (312) 332-3232               None        fralston@gmail.com   
9   +1 (608) 257-0597               None        vstevens@yahoo.com   
10  +1 (817) 924-7272               None  ricunningham@hotmail.com   
11  +1 (520) 622-4200               None      patrick.gray@aol.com   
12  +1 (801) 531-7272               None       jubarnett@gmail.com   

    SupportRepId  
0              4  
1              5  
2              3  
3              3  
4              4  
5              5  
6              4  
7              4  
8              3  
9              5  
10             4  
11             4  
12             5

In [104]:
con.close()

## Sklearn Foundation


Model: linear regression

In [107]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
import pandas as pd


model1 = LinearRegression()

model2 = LinearRegression()

In [108]:
## read csv data from github: mtcars
url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

mtcars.head(2)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0      Mazda RX4  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4   
1  Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4   

   carb  
0     4  
1     4

In [111]:
# ML Workflow
## 4 steps: splits > train > score > evaluate

y = mtcars["mpg"]
X = mtcars[["hp","wt","am"]]

## 1. split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size =0.20, random_state=19
)

## 2. train model
model = LinearRegression()
model.fit(X_train,y_train)  ## model fitting

## 3. score
train_error = model.score(X_train,y_train)
## 4. evaluate
test_error = model.score(X_test,y_test)
print (train_error,test_error)

0.8237392186558011 0.8955384159803106


In [112]:
# ML Workflow
## 4 steps: splits > train > score > evaluate

y = mtcars["mpg"]
X = mtcars[["hp","wt","am"]]

## 1. split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size =0.20, random_state=19
)

## 2. train model
model = RandomForestRegressor()
model.fit(X_train,y_train)  ## model fitting

## 3. score
train_error = model.score(X_train,y_train)
## 4. evaluate
test_error = model.score(X_test,y_test)
print (train_error,test_error)


0.9698830782660216 0.7883799248237494


In [113]:
# ML Workflow
## 4 steps: splits > train > score > evaluate

y = mtcars["mpg"]
X = mtcars[["hp","wt","am"]]

## 1. split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size =0.20, random_state=19
)

## 2. train model
model = DecisionTreeRegressor()
model.fit(X_train,y_train)  ## model fitting

## 3. score
train_error = model.score(X_train,y_train)
## 4. evaluate
test_error = model.score(X_test,y_test)
print (train_error,test_error)

0.9989225398506333 0.5101343642196541
